select * from user_Tables;
CREATE TABLE employer (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(255) NOT NULL,
                          company_name VARCHAR2(255) NOT NULL,
                          email VARCHAR2(100) NOT NULL UNIQUE,
                          password VARCHAR2(255) NOT NULL
);

INSERT INTO employer (id, name, company_name, email, password)
VALUES (1, 'John Doe', 'TechCorp', 'johndoe@techcorp.com', 'employerpassword');

INSERT INTO employer (id, name, company_name, email, password)
VALUES (2, 'Johna Doe', 'Microsoft', 'johnado@microsoft.com', 'employerpass');

select * from employer;

commit;