select * from user_Tables;
CREATE TABLE employer (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(255) NOT NULL,
                          company_name VARCHAR2(255) NOT NULL,
                          email VARCHAR2(100) NOT NULL UNIQUE,
                          password VARCHAR2(255) NOT NULL
);

INSERT INTO employer (id, name, company_name, email, password)
VALUES (1, 'John Doe', 'TechCorp', 'johndoe@techcorp.com', 'employerpassword');

INSERT INTO employer (id, name, company_name, email, password)
VALUES (2, 'Johna Doe', 'Microsoft', 'johnado@microsoft.com', 'employerpass');

CREATE TABLE users (
                      id INT PRIMARY KEY,             -- User ID as primary key
                      email VARCHAR(255) NOT NULL      -- Email as a shared field across all user types
);


INSERT INTO users (id, email)
VALUES (1, 'johndoe@techcorp.com');


select * from employer;

INSERT INTO profile (user_id, bio,  contact_info, first_name, last_name)
VALUES (1,'Employer at TechCorp','johndoe@techcorp.com','John', 'Doe');

commit;